
services:
  bot:
    image: epicpt/weather-bot-bot:latest
    container_name: bot_container
    depends_on:
      - redis
      - postgres
      - prometheus
    env_file: 
      - .env 
    restart: always

    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - bot

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${METRICS_SERVER_ADDR}:${METRICS_SERVER_ADDR}" 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
    - grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - prometheus

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file: 
       - .env 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
  redis_data: